### ISSUE TITLE
Listing charts throws an error

### ISSUE THREAD

**Issue by matiashf** [dhis2/d2#101]
When calling `d2.models.charts.list()` i get the following error:
```
Uncaught (in promise) Error: Can not add a Model without id to a ModelCollection(…)
```
![screenshot from 2016-12-01 15-12-02](https://cloud.githubusercontent.com/assets/29966/20796855/9655dc0a-b7d8-11e6-9a12-5463b5c3a743.png)

I'm testing with d2 version 24.0.13 using [dhis2-app-skeleton](https://github.com/dhis2/app-skeleton) against [the public dhis2 test server](https://play.dhis2.org/test).

Calling `d2.models.charts.list()` works as expected, so the problem is limited to only some models. Since the [API endpoint for charts](https://play.dhis2.org/test/api/charts) returns ids (e.g. `<chart id="LW0O27b7TdD">`) this seems to me like a bug in d2.

**Comment by nicolayr** [comment]
This is caused by special case reference types that are exposed on the charts endpoint. For example the `relativePeriods` property does not contain an `id`, which would cause this error. This is not uncommon across the API, and we implement support for [special cases](https://github.com/dhis2/d2/blob/v25/src/model/ModelDefinition.js#L484) as the need arises. However since our chart apps currently don't use d2, we haven't implemented these special cases either. You are more than welcome to make a pull request though.

To make the query work in d2 now, you can filter out the special case properties from the results, like so:

`d2.models.charts.list({ fields: 'id,displayName', paging: false });`
