### ISSUE TITLE
Headers is experimental with no IE support

### ISSUE THREAD

**Issue by Awnage** [dhis2/d2#97]
I was troubleshooting why a part of my app broke when I looked at the logs and found:

> Deprecation warning: Setting `contentType` for API POST requests is deprecated, and support may be removed in the next major release of D2. In stead you may set the  `Content-Type` header explicitly. 

Okay, fine, but looking at Api.js I see you are using `new Header` which is marked experimental and has no current IE or Webkit support apparently. https://developer.mozilla.org/en-US/docs/Web/API/Headers

Are you planning on continuing to use this experimental feature?

**Comment by nicolayr** [comment]
Hi Greg,

we're also using a polyfill which implements fetch and the related Headers data structure in all browsers that don't support it natively:
https://github.com/github/fetch

You don't need to use Headers in your code though, you can simply pass in a plain JS object and it will be converted to a Headers object for you.

FYI, the only reason why we use the special Headers data structure rather than just a plain JS object is to make sure that it's case insensitive (ie. settings 'Content-Type' and 'content-type' are equivalent).

To answer your question, we do plan on sticking with this approach unless it turns out to be a problem, and it has seemed to work fine so far. Is it causing problems for you?

**Comment by Awnage** [comment]
Well, okay. Using polyfill in a build system does work.
